name: CI

on:
  push:
    branches: [ master ]

jobs:

  build-linux-nix:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - uses: cachix/cachix-action@v10
      with:
        name: futhark
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build Futhark
      run: nix-build --argstr suffix nightly-linux-x86_64 --argstr commit $GITHUB_SHA

    - uses: actions/upload-artifact@v1
      with:
        name: futhark-nightly-linux-x86_64.tar.xz
        path: result/futhark-nightly-linux-x86_64.tar.xz
  
  benchmark-opencl:
    runs-on: [OpenCL]
    needs: [build-linux-nix]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - uses: actions/download-artifact@v3
      with:
        name: futhark-nightly-linux-x86_64.tar.xz

    - name: Install from nightly tarball
      run: |
        tar xvf futhark-nightly-linux-x86_64.tar.xz
        make -C futhark-nightly-linux-x86_64/ install PREFIX=$HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - run: |
        cd futhark-benchmarks
        pwd && ./get-data.sh external-data.txt
    - run: |
        cd futhark-benchmarks
        futhark bench * --backend=opencl --ignore-files /lib/ --json=../benchmark-opencl.json
    - uses: actions/upload-artifact@v3
      with:
        name: benchmark-opencl.json
        path: benchmark-opencl.json
  
  benchmark-cuda:
    runs-on: [CUDA]
    needs: [build-linux-nix]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - uses: actions/download-artifact@v3
      with:
        name: futhark-nightly-linux-x86_64.tar.xz

    - name: Install from nightly tarball
      run: |
        tar xvf futhark-nightly-linux-x86_64.tar.xz
        make -C futhark-nightly-linux-x86_64/ install PREFIX=$HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - run: |
        cd futhark-benchmarks
        pwd && ./get-data.sh external-data.txt
    - run: |
        cd futhark-benchmarks
        futhark bench * --backend=cuda --ignore-files /lib/ --json=../benchmark-cuda.json
    - uses: actions/upload-artifact@v3
      with:
        name: benchmark-cuda.json
        path: benchmark-cuda.json

  benchmark-multicore:
    runs-on: [Multicore]
    needs: [build-linux-nix]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - uses: actions/download-artifact@v3
      with:
        name: futhark-nightly-linux-x86_64.tar.xz

    - name: Install from nightly tarball
      run: |
        tar xvf futhark-nightly-linux-x86_64.tar.xz
        make -C futhark-nightly-linux-x86_64/ install PREFIX=$HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Getting benchmark data
      run: |
        cd futhark-benchmarks
        pwd && ./get-data.sh external-data.txt
    
    - name: Running benchmark
      run: |
        cd futhark-benchmarks
        futhark bench * --no-tuning --backend=multicore --ignore-files /lib/ --json=../benchmark-multicore.json
    
    - name: 
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-multicore.json
        path: benchmark-multicore.json