name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-linux-nix:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Download Futhark
      run: wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz

    - uses: actions/upload-artifact@v1
      with:
        name: futhark-nightly-linux-x86_64.tar.xz
        path: futhark-nightly-linux-x86_64.tar.xz

  benchmark-titanx-cuda:
    runs-on: [titanx]
    needs: [build-linux-nix]
    if: github.repository == 'SelfHostedRunnerTest/futhark' && !github.event.pull_request.draft
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: ./.github/actions/benchmark
      with:
        backend: cuda
        system: titanx
        gpu: titanx

  benchmark-titanrtx-opencl:
    runs-on: [titanrtx]
    needs: [build-linux-nix]
    if: github.repository == 'SelfHostedRunnerTest/futhark' && !github.event.pull_request.draft
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: ./.github/actions/benchmark
      with:
        backend: opencl
        system: titanrtx
        gpu: titanrtx:1
  
  benchmark-results:
    runs-on: ubuntu-22.04
    needs: [benchmark-titanrtx-opencl, benchmark-titanx-cuda]
    if: github.ref == 'refs/heads/master' && ${{ always() }}
    steps:
    - uses: actions/download-artifact@v3
    - run: |
        ls -R
    - name: Prepare package
      run: |
        mkdir -p package
        cp */futhark-*.json package/
        tar -zcvf result.tar.gz package/
    - name: 
      uses: actions/upload-artifact@v3
      with:
        name: result.tar.gz
        path: result.tar.gz
