name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: diku-dk/futhark-ci@main
        with:
          inputs:
            myInput: write

      - name: Check outputs
        run: test "${{ steps.selftest.outputs.myOutput }}" == "write"
