name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: diku-dk/futhark-ci@main
          with:
            permission: write

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.permission }}" == "write"
